const VALID_SCOPES = {
    CHANNEL: 'CHANNEL',
    DM: 'DM',
};

const PLAYER_STATUS = {
    WAITING: 'WAITING',
    PLAYING: 'PLAYING',
    FINISHED: 'FINISHED',
}

const PAGE_STATUS = {
    PENDING: 'PENDING',
    DELIVERED: 'DELIVERED',
}

const CONTENT_TYPES = {
    TEXT: 'TEXT',
    IMAGE: 'IMAGE',
}


module.exports = { CONTENT_TYPES, PAGE_STATUS, PLAYER_STATUS, VALID_SCOPES };